services:
  server:
    build:
      context: .
      target: final
    ports:
      - 3334:3334
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./.env
        target: /bin/.env
  postgres:
    image: postgres:latest
    shm_size: 16g
    container_name: postgres_db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./postgres_data:/var/lib/postgresql/data